[package]
name = "bian-front-wasm"
version = "1.0.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }
bian-lang = {path="../bian-lang"}
